version: 0.2
env:
  secrets-manager:
    TOKEN: scb/dev/sonar:sonartoken
    HOST: scb/dev/sonar:HOST
    Organization: scb/dev/sonar:Organization
phases:
  install:
    runtime-versions:
      java: openjdk8
      python: 3.9
      nodejs: latest
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
      - pip3 install pysonar-scanner
  build:
    commands:
      - export Project=webapp 
      - export SONAR_HOST_URL=$HOST
      - pysonar-scanner -Dsonar.token=$TOKEN -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >reports/result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi

artifacts:
  files:
    - '**/*'
reports:
  sonar-sast-reports:
    files:
    - "./reports/result.json"