version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo install pre_build requirements
  pre_build:
    commands:
      - |
        #!/bin/bash
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        source ~/.bashrc
        nvm install 16
        nvm use 16
        npm install -g pm2
  
  build:
    commands:
      - |
        cd ~/
        echo $APP_BUCKET_NAME
        aws s3 cp app-tier s3://$APP_BUCKET_NAME/app-tier/ --recursive
        