version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    GITLEAKS_VERSION: "8.18.4"

phases:
  build:
    commands:
      - "wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz"
      - "tar -xzf gitleaks_8.18.4_linux_x64.tar.gz"
      - ls -al
      - "mv gitleaks /bin"
      - "rm gitleaks_8.18.4_linux_x64.tar.gz"
      - pwd
      - "gitleaks detect --report-path reports/gitleaks-report.json"

artifacts:
  files:
    - '**/*'
reports:
  gitleaks-reports:
    files:
      - "./reports/gitleaks-report.json"