version: 0.2

env:
    variables:
      TF_VERSION: "1.7.2"

phases:
  pre_build:
    commands:
      - echo install Terraform...
      - "curl -s -qL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - cd /tmp
      - "unzip -o terraform.zip"
      - "mv terraform /bin"
      - "rm terraform.zip"


  build:
    commands:
      - echo Terraform apply started on `date`
      - cd -
      - cd terraform
      - ./terraform_init_$TARGET_ENV.sh
      - terraform workspace select $TARGET_ENV
      - terraform apply ./output_plan_$TARGET_ENV.tfplan

  post_build:
    commands:
      - ls -lsa
      - pwd
