version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - ""curl -s -qL -o gitleaks.zip https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_arm64.tar.gz"
      - "unzip -o gitleaks.zip"
      - "mv gitleaks/gitleaks /bin"
      - "rm gitleaks.zip"
  build:
    commands:
      - pwd
      - "gitleaks detect --report-path reports/gitleaks-report.json"

artifacts:
  files:
    - '**/*'
reports:
  gitleaks-reports:
    files:
      - "./reports/gitleaks-report.json"