version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    GITLEAKS_VERSION: "8.18.4"

phases:
  install:
    runtime-versions:
      golang: 1.14
  build:
    commands:
      - "curl -s -qL -o gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_8.18.4_linux_arm64.tar.gz"
      - "unzip -o gitleaks.tar.gz"
      - "mv gitleaks/gitleaks /bin"
      - "rm gitleaks.zip"
      - pwd
      - "gitleaks detect --report-path reports/gitleaks-report.json"

artifacts:
  files:
    - '**/*'
reports:
  gitleaks-reports:
    files:
      - "./reports/gitleaks-report.json"