version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - "git clone https://github.com/gitleaks/gitleaks.git"
      - "cd gitleaks"
      - "make build"
  build:
    commands:
      - pwd
      - "gitleaks detect --report-path reports/gitleaks-report.json"

artifacts:
  files:
    - '**/*'
reports:
  gitleaks-reports:
    files:
      - "./reports/gitleaks-report.json"